Table\RestaurantBundle\Entity\TableOrder:
    properties:
        peopleCount:
            - NotBlank: ~
        tableNumber:
            - NotBlank: ~
        reserveDate:
            - Date: ~
        reserveTime:
            - Time: ~
            
Table\RestaurantBundle\Entity\ActiveTableOrder:
    properties:
        peopleCount:
            - NotBlank: ~
        reserveDate:
            - Date: ~
        reserveTime:
            - Time: ~
        activeTable:
            - NotBlank: ~    
        tableNumber:
            - NotBlank: ~      
            
