<?php

namespace Table\RestaurantBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Table\RestaurantBundle\Entity\ActiveTableOrder;

/**
 * TableOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiveTableOrderRepository extends EntityRepository
{

    /**
     *  Filter Order History
     * 
     * @param integer $user
     * 
     * @param Request $request
     * 
     * @param integer $orderStatus
     * 
     * @return Table\RestaurantBundle\Entity\Repository[]
     */
    public function filterOrderHistory($user, $request, $orderStatus = null)
    {
        $filterDate = $request->query->get('filterDate');
        $searchStr = $request->query->get('searchStr');

        $query = $this->createQueryBuilder('orderHistory')
                ->where('orderHistory.user = :user')
                ->setParameter('user', $user);
        if (!is_null($orderStatus)) {
            $query->andWhere('orderHistory.status = :orderStatus')
                    ->setParameter('orderStatus', $orderStatus);
        }

        if (!is_null($filterDate) && $filterDate != "") {
            $query->andWhere('orderHistory.reserveDate = :reserveDate')
                    ->setParameter('reserveDate', $filterDate);
        }
        if (!is_null($searchStr) && $searchStr != "") {
            $query->leftJoin('orderHistory.activeTable', 'activeTable')
                    ->leftJoin('activeTable.tableMap', 'tableMap')
                    ->leftJoin('tableMap.restaurant', 'restaurant')
                    ->leftJoin('restaurant.city', 'city')
                    ->andWhere("restaurant.name like '%$searchStr%' or city.name like '%$searchStr%' or restaurant.street like '%$searchStr%'");
        }

        return $query;
    }

    /**
     * 
     * Get Order History
     * 
     * @param integer $user
     * 
     * @param integer $orderStatus
     * 
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getOrderHistory($user, $orderStatus = null)
    {
        $query = $this->createQueryBuilder('tableOrder');
        $query->where('tableOrder.user = :user')
                ->setParameter('user', $user);
        if (!is_null($orderStatus)) {
            $query->andWhere('tableOrder.status = :orderStatus')
                    ->setParameter('orderStatus', $orderStatus);
        }

        return $query;
    }

    /**
     *  Check if user can order table
     * 
     * @param integer $user
     * 
     * @param \DateTime $reserveDateTime
     * 
     * @return Table\RestaurantBundle\Entity\Repository[]
     */
    public function isUserCanReserveTable($user, $reserveDateTime = null)
    {
        // get current time
        $currentDateTime = new \DateTime("now");
        if (is_null($reserveDateTime)) {
            $reserveDateTime = $currentDateTime;
        }
        
        // Check rule
        // 1. Guest can book a table in the period till 16-00 not later than 30 minutes
        // In the period from 16-00 guest cannot be booked later than 1 hour
        
        // Get interval between current time and booked time
        $interval = $currentDateTime->diff($reserveDateTime); // invert mustn't be 1
        if ($interval->invert == 1) {
            return false;
        }
        $time = $reserveDateTime->format("H:i");   
        switch (true) {
            case ($time < "16:00") :           
                if ($interval->y == 0 && 
                        $interval->m == 0 && 
                        $interval->d == 0 && 
                        $interval->h == 0 &&
                        $interval->i < 30) {
                    return false;
                }
                break;
            case ($time >= "16:00") :       
                if ($interval->y == 0 && 
                        $interval->m == 0 && 
                        $interval->d == 0 && 
                        $interval->h < 1) {
                    return false;
                }
                break;
        }
        $query = $this->createQueryBuilder('orderHistory')
                // for define user
                ->where('orderHistory.user = :user')
                ->setParameter('user', $user);

        // Check only for complete and not processed order
        $query->andWhere('orderHistory.status = 0 or orderHistory.status=2');

        // check date. Search for the same date and time[+-1 h]
        $query->andWhere('orderHistory.reserveDate = :reserveDate')
                ->setParameter('reserveDate', $reserveDateTime->format('Y-m-d'));

        // get start time
        $startTime = clone $reserveDateTime; // first init
        $startTime->modify("-60 minutes");
        // get end time
        $endTime = clone $reserveDateTime; // first init
        $endTime->modify("+60 minutes");

        $query->andWhere('orderHistory.reserveTime BETWEEN :startTime AND :endTime')
                ->setParameter('startTime', $startTime->format('H:i:s'))
                ->setParameter('endTime', $endTime->format('H:i:s'));

        $result = $query->getQuery()->getResult();

        if (count($result) == 0) {
            return true;
        } else {
            return false;
        }
    }
    
    /**
     *  Get Free Booked By restaurant
     * 
     * @param integer $id 
     * 
     * @param \DateTime $dateTime 
     * 
     * @return Table\RestaurantBundle\Entity\Repository[]
     */
    public function getBookedTablesByRestaurant($id, $dateTime = null)
    {
        $query = $this->createQueryBuilder('activeTableOrder')
                ->select('activeTable.id')
                ->leftJoin('activeTableOrder.activeTable', 'activeTable')
                ->leftJoin('activeTable.tableMap', 'tableMap')
                ->leftJoin('tableMap.restaurant', 'restaurant')
                ->where("restaurant.id = :restaurantId")
                ->setParameter('restaurantId', $id);
        
        if (is_null($dateTime)) {
            $dateTime = new \DateTime("now");
        }
        $startTime = clone $dateTime; // first init
        $endTime = clone $dateTime; // first init
        // devide on date & time
        $date = $dateTime->format("Y-m-d");
        $time = $dateTime->format("H:i");    
        switch (true) {
            case ($time < "16:00") :           
                // get start time (+-1.5h)
                $startTime->modify("-90 minutes");
                // get end time
                $endTime->modify("+90 minutes"); 
                break;
            case ($time >= "16:00" && $time < "19:00") :
                // get start time (+-2.5h)
                $startTime->modify("-150 minutes");
                // get end time
                $endTime->modify("+150 minutes");
                break;
            case ($time >= "19:00") :       
                // modify only end time
                $endTime->setTime(23, 59);
                break;
        }  
        $query->andWhere('activeTableOrder.reserveDate = :reserveDate')
              ->setParameter('reserveDate', $date)
              ->andWhere('activeTableOrder.reserveTime BETWEEN :startTime AND :endTime')
              ->setParameter('startTime', $startTime->format('H:i:s'))
              ->setParameter('endTime', $endTime->format('H:i:s'))
              ->distinct('activeTable.id');

        return $query->getQuery()->getResult();
    }
    
    /**
     * 
     * Get Order History by Active Table
     * 
     * @param integer $activeTable
     * 
     * 
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getActiveTableOrderHistory($activeTable)
    {
        $query = $this->createQueryBuilder('tableOrder');
        $query->where('tableOrder.activeTable = :activeTable')
                ->setParameter('activeTable', $activeTable);
        
        // Show all completed and not processed orders
        $orderNothingDidStatus = ActiveTableOrder::ORDER_NOTHING_DID_STATUS_CODE;
        $orderAcceptStatus = ActiveTableOrder::ORDER_ACCEPT_STATUS_CODE;
        $query->andWhere('tableOrder.status = :orderNothingDidStatus OR tableOrder.status = :orderAcceptStatus')
              ->setParameter('orderNothingDidStatus', $orderNothingDidStatus)
              ->setParameter('orderAcceptStatus', $orderAcceptStatus);  
        
        // Show only actual orders, not earlier that now
        // Get current DateTime
        $currentDateTime = new \DateTime("now");
        $currentDate = $currentDateTime->format("Y-m-d");
        $currentTime = $currentDateTime->format("H:i");
        $query->andWhere('(tableOrder.reserveDate > :currentDate) OR (tableOrder.reserveDate = :currentDate AND tableOrder.reserveTime > :currentTime)')
              ->setParameter('currentDate', $currentDate)
              ->setParameter('currentTime', $currentTime); 
        
        $query->orderBy('tableOrder.reserveDate, tableOrder.reserveTime', 'ASC');

        return $query->getQuery()->getResult();
    }

}
