<?php

namespace Table\RestaurantBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RatingStatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingStatRepository extends EntityRepository
{
    /**
     *  Get User 2 Restaurant stat
     * 
     * @return Table\RestaurantBundle\Entity\Repository[]
     */
    public function getUser2RestaurantRating($userId, $restaurantId)
    {
        return $this->findOneBy(array(
            'user' => $userId, 
            'restaurant' => $restaurantId
        ));
        
    }
    
    /**
     *  Get User 2 Restaurant stat
     * 
     * @return Table\RestaurantBundle\Entity\Repository[]
     */
    public function getUserRestaurantRating($userId, $dateTime)
    {
        $query = $this->createQueryBuilder('restaurant')
            ->select('DISTINCT(restaurant.city)') 
            ->orderBy('restaurant.name', 'ASC')
            ->getQuery();
        
        return $query->getResult();
    }
}
