<?php

namespace Table\RestaurantBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RatingStatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingStatRepository extends EntityRepository
{
    /**
     *  Get User 2 Restaurant stat
     * 
     * @return Table\RestaurantBundle\Entity\Repository[]
     */
    public function getUser2RestaurantRating($userId, $restaurantId)
    {
        return $this->findOneBy(array(
            'user' => $userId, 
            'restaurant' => $restaurantId
        ));
        
    }
    
    /**
     *  Get User To Restaurant stat
     * 
     * @return Table\RestaurantBundle\Entity\Repository[]
     */
    public function getUserRestaurantRating($user)
    {
        $query = $this->createQueryBuilder('rating')
                ->where('rating.user = :user')
                ->setParameter('user', $user)
                ->andWhere('rating.lastUpdateTime >= :nowTime')
                ->setParameter('nowTime', new \DateTime())
                ->getQuery();  

        return $query->getResult();
    }
}
