<?php

namespace Table\RestaurantBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RestaurantKitchenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantKitchenRepository extends EntityRepository
{
    /**
     * 
     * Get Kitchens
     * 
     * @return Table\RestaurantBundle\Entity\RestaurantKitchen[]
     */
    public function getKitchens()
    {
        $query = $this->createQueryBuilder('restaurantKitchen');
        $query->orderBy('restaurantKitchen.name');
        return $query->getQuery()->getResult();
    }
}
