<?php

namespace Table\RestaurantBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RestaurantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantRepository extends EntityRepository
{
    /**
     * 
     * Get Restaurants
     * 
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getRestaurants() 
    {
        $query = $this->createQueryBuilder('restaurant');
        $query->orderBy('restaurant.name', 'ASC');
 
        return $query;
    }
    
    /**
     *  Get regions
     * 
     * @return Table\RestaurantBundle\Entity\Repository[]
     */
    public function getCitiesList()
    {
        $query = $this->createQueryBuilder('restaurant')
            ->select('DISTINCT(restaurant.city)') 
            ->orderBy('restaurant.name', 'ASC')
            ->getQuery();
        
        return $query->getResult();
    }
    
    /**
     * 
     * Search Restaurants
     * 
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function searchRestaurants($request) 
    { 
        // collect parametres
        $requestParametres = $request->request->all();  
        $query = $this->createQueryBuilder('restaurant');
        $searchStr = $requestParametres['searchStr'];
        $categoriesList = $requestParametres['categoriesList'];
        $kitchensList = $requestParametres['kitchensList'];
        if (!is_null($searchStr)) {
            $query->where('restaurant.name like "%:operation%"')
            ->setParameter('operation', $propertyOperation);
        }
        
        
        $query->orderBy('restaurant.name', 'ASC');

        return $query;
    }
}
