<?php

namespace Table\RestaurantBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TableMapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableMapRepository extends EntityRepository
{
    /**
     * 
     * Get ordered table map list
     * 
     * @param type $restaurantId
     * 
     * @return Table\RestaurantBundle\Entity\Repository[]
     */
    public function getTableMapList($restaurantId)
    {
        $query = $this->createQueryBuilder('tableMap')
                ->andWhere("tableMap.restaurant = :restaurantId")
                ->setParameter('restaurantId', $restaurantId)
                ->orderBy('tableMap.floor, tableMap.hall', 'ASC');
        
        return $query->getQuery()->getResult();
    }
    
    /**
     * 
     * Get ordered table map list
     * 
     * @param type $restaurantId
     * 
     * @return Table\RestaurantBundle\Entity\Repository[]
     */
    public function getRestaurantTableMapFloorList($restaurantId)
    {
        $query = $this->createQueryBuilder('tableMap')
                ->select('tableMap.floor')
                ->where("tableMap.restaurant = :restaurantId")
                ->setParameter('restaurantId', $restaurantId)
                ->distinct('tableMap.floor')
                ->orderBy('tableMap.floor', 'ASC');
        
        return $query->getQuery()->getResult();
    }
    
    /**
     * 
     * Get ordered table map list
     * 
     * @param type $restaurantId
     * 
     * @param integer $floor
     * 
     * @return Table\RestaurantBundle\Entity\Repository[]
     */
    public function getTableMapListByFloorGroupByHall($restaurantId, $floor)
    {
        $query = $this->createQueryBuilder('tableMap')
                ->where("tableMap.restaurant = :restaurantId")
                ->setParameter('restaurantId', $restaurantId)
                ->andWhere("tableMap.floor = :floor")
                ->setParameter('floor', $floor)
                ->orderBy('tableMap.hall', 'ASC');
        
        return $query->getQuery()->getResult();
    }
}
