<?php

namespace Table\RestaurantBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TableOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableOrderRepository extends EntityRepository
{
    /**
     * 
     * Get Order History
     * 
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getOrderHistory($user) 
    {
        $query = $this->createQueryBuilder('tableOrder');
        $query->where('tableOrder.user = :user')
              ->setParameter('user', $user);
 
        return $query;
    }
    
    /**
     *  Filter Order History
     * 
     * @param integer $user
     * @param string $filterDate
     * @param string $searchStr
     * 
     * @return Table\RestaurantBundle\Entity\Repository[]
     */
    public function filterOrderHistory($user, $filterDate = null, $searchStr = null)
    {

        $query = $this->createQueryBuilder('orderHistory')
                ->where('orderHistory.user = :user')
                ->setParameter('user', $user);
	if (!is_null($filterDate) && $filterDate != "") {
		$query->andWhere('orderHistory.reserveDate = :reserveDate')
                      ->setParameter('reserveDate', $filterDate);
	}
	if (!is_null($searchStr) && $searchStr != "") {
		$query->leftJoin('orderHistory.restaurant', 'restaurant')
              ->leftJoin('restaurant.city', 'city')        
		      ->andWhere("restaurant.name like '%$searchStr%' or city.name like '%$searchStr%' or restaurant.street like '%$searchStr%'");
		//$query->leftJoin('orderHistory.restaurant.categories', 'c');
		
	}
      //  $query->getQuery();  
//var_dump($query->getQuery()->getResult()); die();
        return $query->getQuery()->getResult();
    }
}
