<?php

namespace Table\RestaurantBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TableOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableOrderRepository extends EntityRepository
{
    /**
     * 
     * Get Order History
     * 
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getOrderHistory($user) 
    {
        $query = $this->createQueryBuilder('tableOrder');
        $query->where('tableOrder.user = :user')
              ->setParameter('user', $user);
 
        return $query;
    }
}
