   
table_api:
    resource: "@TableApiBundle/Resources/config/routing.yml"
    prefix:   /
    
table_restaurant:
    resource: "@TableRestaurantBundle/Resources/config/routing.yml"
    prefix:   /

table_main:
    resource: "@TableMainBundle/Resources/config/routing.yml"
    prefix:   /

sonata_admin_dashboard_custom:
    pattern:  /table_admin/
    defaults: { _controller: SonataAdminBundle:Core:dashboard }

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /table_admin

table_admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /table_admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /table_admin

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

fos_user_security:
    #resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    resource: "@SonataUserBundle/Resources/config/routing.yml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"    
gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login
 
hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login
 
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login
 
facebook_login:
    pattern: /login/check-facebook
 
twitter_login:
    pattern: /login/check-twitter

vkontakte_login:
    pattern: /login/check-vkontakte    