Table\RestaurantBundle\Entity\City:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            inline: true
        name:
            expose: true
            serialized_name: name