Table\CoreDomain\TableOrder\TableOrder:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            inline: true
            serialized_name: id
        restaurantMap:
            expose: true
            serialized_name: restaurantMap
        floors:
            expose: true
            serialized_name: floors