Table\CoreDomain\TableOrder\TableOrder:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            serialized_name: id
        date:
            expose: true
            serialized_name: date
        time:
            expose: true
            serialized_name: time
        name:
            expose: true
            serialized_name: name
        address:
            expose: true
            serialized_name: address    