table_main_homepage:
    pattern:  /{page}
    defaults: { _controller: TableMainBundle:Default:index, page: 1 }
    requirements:
        page: \d+   
    options:
       expose: true       

table_main_auth_page:
    pattern:  /viewAuthPage
    defaults: { _controller: TableMainBundle:Default:viewAuthPage }

table_main_validate_user_email:
    pattern: /validateUserEmail/{path}
    defaults: { _controller: TableMainBundle:Default:validateUserEmail }
    options:
       expose: true 