parameters:
#    table_main.example.class: Table\MainBundle\Example

services:
  restaurant_manager:
        class: Table\RestaurantBundle\Model\RestaurantManager
        arguments: [@doctrine.orm.entity_manager, @service_container]   