parameters:
#    table_main.example.class: Table\MainBundle\Example

services:
  restaurant_manager:
        class: Table\RestaurantBundle\Model\RestaurantManager
        arguments: [@doctrine.orm.entity_manager, @service_container]   
  restaurant_category_manager:
        class: Table\RestaurantBundle\Model\RestaurantCategoryManager
        arguments: [@doctrine.orm.entity_manager, @service_container]    
  restaurant_kitchen_manager:
        class: Table\RestaurantBundle\Model\RestaurantKitchenManager
        arguments: [@doctrine.orm.entity_manager, @service_container] 
  restaurant_additional_service_manager:
        class: Table\RestaurantBundle\Model\RestaurantAdditionalServiceManager
        arguments: [@doctrine.orm.entity_manager, @service_container]     
  table_order_manager:
        class: Table\RestaurantBundle\Model\TableOrderManager
        arguments: [@doctrine.orm.entity_manager, @service_container]   
  rating_stat_manager:
        class: Table\RestaurantBundle\Model\RatingStatManager
        arguments: [@doctrine.orm.entity_manager, @service_container]       