# Api for user
table_api.login:
    pattern: /api/rest/login
    defaults: { _controller: TableApiBundle:User:login, _format: json }
    requirements:
        _method: POST  
 
table_api.logout:
    pattern: /api/rest/logout
    defaults: { _controller: TableApiBundle:User:logout, _format: json }
    requirements:
        _method: POST  
      
table_api.getUserInfo:
    pattern:  /api/rest/wsse/getUserInfo
    defaults: { _controller: TableApiBundle:User:getUserInfo, _format: json }
    requirements:
        _method: GET         
        
table_api.forgotPassword:
    pattern:  /api/rest/forgotPassword
    defaults: { _controller: TableApiBundle:User:forgotPassword, _format: json }
    requirements:
        _method: POST   
        
table_api_register:
    pattern:  /api/rest/register
    defaults: { _controller: TableApiBundle:User:register, _format: json }
    requirements:
        _method: POST   
                  

# Api for Restaurnat
table_api.cities_all:
    pattern:  /api/rest/getCitiesList
    defaults: { _controller: TableApiBundle:Restaurant:getCitiesList, _format: json }
    requirements:
        _method: GET  
        
table_api.restaurant_all:
    pattern:  /api/rest/getRestaurants/{city}
    defaults: { _controller: TableApiBundle:Restaurant:getRestaurants, city: null, _format: json }
    requirements:
        _method: GET    

table_api.restaurant_one:
    pattern:  /api/rest/getRestaurantById/{id}
    defaults: { _controller: TableApiBundle:Restaurant:getRestaurantById, _format: json }
    requirements:
        _method: GET   
        id: "\d+"
        
table_api.restaurant_geo_all:
    pattern:  /api/rest/geoSearch/{city}
    defaults: { _controller: TableApiBundle:Restaurant:geoSearch, city: null, _format: json }
    requirements:
        _method: GET   

table_api.restaurant_search:
    pattern:  /api/rest/search
    defaults: { _controller: TableApiBundle:Restaurant:search, _format: json }
    requirements:
        _method: POST   

table_api.restaurant_get_menu_photos:
    pattern:  /api/rest/getMenuPhotos/{restaurantId}
    defaults: { _controller: TableApiBundle:Restaurant:getMenuPhotos, _format: json }
    requirements:
        _method: GET   
        id: "\d+" 
  
table_api.restaurant_get_additional_photos:
    pattern:  /api/rest/getAdditionalPhotos/{restaurantId}
    defaults: { _controller: TableApiBundle:Restaurant:getAdditionalPhotos, _format: json }
    requirements:
        _method: GET   
        id: "\d+"         
        
# Api for Restaurant category
table_api.restaurant_categories_all:
    pattern:  /api/rest/getCategoriesList
    defaults: { _controller: TableApiBundle:RestaurantCategory:getCategoriesList, _format: json }
    requirements:
        _method: GET    
        
# Api for Restaurant kitchen
table_api.restaurant_kitchens_all:
    pattern:  /api/rest/getKitchensList
    defaults: { _controller: TableApiBundle:RestaurantKitchen:getKitchensList, _format: json }
    requirements:
        _method: GET        
        
# Api for Restaurant additional service
table_api.restaurant_additional_services_all:
    pattern:  /api/rest/getAdditionalServicesList
    defaults: { _controller: TableApiBundle:RestaurantAdditionalService:getAdditionalServicesList, _format: json }
    requirements:
        _method: GET     
 
# Api for Order History      
table_api.orders_all:
    pattern:  /api/rest/wsse/getOrderHistory
    defaults: { _controller: TableApiBundle:TableOrder:getOrderHistory, _format: json }
    requirements:
        _method: GET    
  
# Api for Reserve   
table_api.view_reserve:
    pattern:  /api/rest/wsse/viewReserve/{restaurantId}
    defaults: { _controller: TableApiBundle:TableReserve:viewReserve, _format: json }
    requirements:
        _method: GET
        
table_api.view_reserve:
    pattern:  /api/rest/wsse/reserve
    defaults: { _controller: TableApiBundle:TableReserve:reserve, _format: json }
    requirements:
        _method: POST        
        
# Api for News     
table_api.news_all:
    pattern:  /api/rest/getNewsList/{restaurantId}
    defaults: { _controller: TableApiBundle:TableNews:getNewsList, _format: json }
    requirements:
        _method: GET   
        
table_api.news_one:
    pattern:  /api/rest/getNewsById/{id}
    defaults: { _controller: TableApiBundle:TableNews:getNewsById, _format: json }
    requirements:
        _method: GET   
        id: "\d+"        
