fos_user_security_login:
    pattern:  /login
    defaults: { _controller: SonataUserBundle:Security:login } 

fos_user_security_check:
    pattern:  /login_check
    defaults: { _controller: SonataUserBundle:Security:check }     

fos_user_security_logout:
    pattern:  /logout
    defaults: { _controller: FOSUserBundle:Security:logout }  
    
fos_user_profile_show:
    pattern:  /profile
    defaults: { _controller: FOSUserBundle:Profile:show }  

sonata_user_profile_show:
    pattern:  /profile/{page}
    defaults: { _controller: ApplicationSonataUserBundle:Profile:showProfile, page: 1 }           