fos_user_security_login:
    pattern:  /login
    defaults: { _controller: SonataUserBundle:Security:login } 
    options:
       expose: true

fos_user_security_check:
    pattern:  /login_check
    defaults: { _controller: SonataUserBundle:Security:check }     

fos_user_security_logout:
    pattern:  /logout
    defaults: { _controller: FOSUserBundle:Security:logout }  
    
fos_user_profile_show:
    pattern:  /profile
    defaults: { _controller: FOSUserBundle:Profile:show }     
       
fos_user_profile_edit:
    pattern:  /edit-profile
    defaults: { _controller: SonataUserBundle:Profile:editProfile }     
    options:
       expose: true      
 
fos_user_registration_register_custom:       
    pattern:  /register
    defaults: { _controller: SonataUserBundle:Registration:register }     
    options:
       expose: true

fos_user_check_resetting_code:
    pattern:  /checkResettingCode
    defaults: { _controller: SonataUserBundle:Resetting:checkResettingCode }     
    options:
       expose: true

fos_user_resetting_send_code:
    pattern:  /resetting/send-code
    defaults: { _controller: SonataUserBundle:Resetting:sendResettingCode }     
    options:
       expose: true

fos_user_resetting_reset_password:
    pattern:  /resetting/reset
    defaults: { _controller: SonataUserBundle:Resetting:resetUserPassword }     
    options:
       expose: true
       
sonata_user_profile_edit:
    pattern:  /profile/edit
    defaults: { _controller: ApplicationSonataUserBundle:Profile:editProfile }     
    options:
       expose: true            