fos_user_security_login:
    pattern:  /login
    defaults: { _controller: SonataUserBundle:Security:login } 

fos_user_security_check:
    pattern:  /login_check
    defaults: { _controller: FOSUserBundle:Security:check }     

fos_user_security_logout:
    pattern:  /logout
    defaults: { _controller: FOSUserBundle:Security:logout }  